// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: kubebrainz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusResponse_State int32

const (
	GetStatusResponse_STATE_UNSPECIFIED GetStatusResponse_State = 0
	GetStatusResponse_STATE_DOWNLOADING GetStatusResponse_State = 1
	GetStatusResponse_STATE_LOADING     GetStatusResponse_State = 2
	GetStatusResponse_STATE_SERVING     GetStatusResponse_State = 3
)

// Enum value maps for GetStatusResponse_State.
var (
	GetStatusResponse_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_DOWNLOADING",
		2: "STATE_LOADING",
		3: "STATE_SERVING",
	}
	GetStatusResponse_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_DOWNLOADING": 1,
		"STATE_LOADING":     2,
		"STATE_SERVING":     3,
	}
)

func (x GetStatusResponse_State) Enum() *GetStatusResponse_State {
	p := new(GetStatusResponse_State)
	*p = x
	return p
}

func (x GetStatusResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStatusResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_kubebrainz_proto_enumTypes[0].Descriptor()
}

func (GetStatusResponse_State) Type() protoreflect.EnumType {
	return &file_kubebrainz_proto_enumTypes[0]
}

func (x GetStatusResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStatusResponse_State.Descriptor instead.
func (GetStatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{1, 0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_kubebrainz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string                  `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	State   GetStatusResponse_State `protobuf:"varint,2,opt,name=state,proto3,enum=kubebrainz.GetStatusResponse_State" json:"state,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_kubebrainz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetState() GetStatusResponse_State {
	if x != nil {
		return x.State
	}
	return GetStatusResponse_STATE_UNSPECIFIED
}

type GetArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist            string `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	AllowSuffixSquash bool   `protobuf:"varint,2,opt,name=allow_suffix_squash,json=allowSuffixSquash,proto3" json:"allow_suffix_squash,omitempty"`
}

func (x *GetArtistRequest) Reset() {
	*x = GetArtistRequest{}
	mi := &file_kubebrainz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistRequest) ProtoMessage() {}

func (x *GetArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistRequest.ProtoReflect.Descriptor instead.
func (*GetArtistRequest) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtistRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *GetArtistRequest) GetAllowSuffixSquash() bool {
	if x != nil {
		return x.AllowSuffixSquash
	}
	return false
}

type GetArtistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtistSort string `protobuf:"bytes,1,opt,name=artist_sort,json=artistSort,proto3" json:"artist_sort,omitempty"`
}

func (x *GetArtistResponse) Reset() {
	*x = GetArtistResponse{}
	mi := &file_kubebrainz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistResponse) ProtoMessage() {}

func (x *GetArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistResponse.ProtoReflect.Descriptor instead.
func (*GetArtistResponse) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtistResponse) GetArtistSort() string {
	if x != nil {
		return x.ArtistSort
	}
	return ""
}

var File_kubebrainz_proto protoreflect.FileDescriptor

var file_kubebrainz_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x22, 0x12,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5b, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f,
	0x41, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f,
	0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78,
	0x53, 0x71, 0x75, 0x61, 0x73, 0x68, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x32, 0xab, 0x01, 0x0a,
	0x11, 0x4b, 0x75, 0x62, 0x65, 0x42, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6b, 0x75,
	0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6b, 0x75, 0x62, 0x65,
	0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kubebrainz_proto_rawDescOnce sync.Once
	file_kubebrainz_proto_rawDescData = file_kubebrainz_proto_rawDesc
)

func file_kubebrainz_proto_rawDescGZIP() []byte {
	file_kubebrainz_proto_rawDescOnce.Do(func() {
		file_kubebrainz_proto_rawDescData = protoimpl.X.CompressGZIP(file_kubebrainz_proto_rawDescData)
	})
	return file_kubebrainz_proto_rawDescData
}

var file_kubebrainz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubebrainz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubebrainz_proto_goTypes = []any{
	(GetStatusResponse_State)(0), // 0: kubebrainz.GetStatusResponse.State
	(*GetStatusRequest)(nil),     // 1: kubebrainz.GetStatusRequest
	(*GetStatusResponse)(nil),    // 2: kubebrainz.GetStatusResponse
	(*GetArtistRequest)(nil),     // 3: kubebrainz.GetArtistRequest
	(*GetArtistResponse)(nil),    // 4: kubebrainz.GetArtistResponse
}
var file_kubebrainz_proto_depIdxs = []int32{
	0, // 0: kubebrainz.GetStatusResponse.state:type_name -> kubebrainz.GetStatusResponse.State
	1, // 1: kubebrainz.KubeBrainzService.GetStatus:input_type -> kubebrainz.GetStatusRequest
	3, // 2: kubebrainz.KubeBrainzService.GetArtist:input_type -> kubebrainz.GetArtistRequest
	2, // 3: kubebrainz.KubeBrainzService.GetStatus:output_type -> kubebrainz.GetStatusResponse
	4, // 4: kubebrainz.KubeBrainzService.GetArtist:output_type -> kubebrainz.GetArtistResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubebrainz_proto_init() }
func file_kubebrainz_proto_init() {
	if File_kubebrainz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kubebrainz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubebrainz_proto_goTypes,
		DependencyIndexes: file_kubebrainz_proto_depIdxs,
		EnumInfos:         file_kubebrainz_proto_enumTypes,
		MessageInfos:      file_kubebrainz_proto_msgTypes,
	}.Build()
	File_kubebrainz_proto = out.File
	file_kubebrainz_proto_rawDesc = nil
	file_kubebrainz_proto_goTypes = nil
	file_kubebrainz_proto_depIdxs = nil
}
