// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: kubebrainz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kubebrainz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kubebrainz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artitst           string `protobuf:"bytes,1,opt,name=artitst,proto3" json:"artitst,omitempty"`
	AllowSuffixSquash bool   `protobuf:"varint,2,opt,name=allow_suffix_squash,json=allowSuffixSquash,proto3" json:"allow_suffix_squash,omitempty"`
}

func (x *GetArtistRequest) Reset() {
	*x = GetArtistRequest{}
	mi := &file_kubebrainz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistRequest) ProtoMessage() {}

func (x *GetArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistRequest.ProtoReflect.Descriptor instead.
func (*GetArtistRequest) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtistRequest) GetArtitst() string {
	if x != nil {
		return x.Artitst
	}
	return ""
}

func (x *GetArtistRequest) GetAllowSuffixSquash() bool {
	if x != nil {
		return x.AllowSuffixSquash
	}
	return false
}

type GetArtistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtistSort string `protobuf:"bytes,1,opt,name=artist_sort,json=artistSort,proto3" json:"artist_sort,omitempty"`
}

func (x *GetArtistResponse) Reset() {
	*x = GetArtistResponse{}
	mi := &file_kubebrainz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistResponse) ProtoMessage() {}

func (x *GetArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubebrainz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistResponse.ProtoReflect.Descriptor instead.
func (*GetArtistResponse) Descriptor() ([]byte, []int) {
	return file_kubebrainz_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtistResponse) GetArtistSort() string {
	if x != nil {
		return x.ArtistSort
	}
	return ""
}

var File_kubebrainz_proto protoreflect.FileDescriptor

var file_kubebrainz_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2a, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x74, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x74, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x75, 0x66,
	0x66, 0x69, 0x78, 0x53, 0x71, 0x75, 0x61, 0x73, 0x68, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x32,
	0x9e, 0x01, 0x0a, 0x0d, 0x50, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x6b, 0x75,
	0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61,
	0x69, 0x6e, 0x7a, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x1c, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6b, 0x75, 0x62, 0x65,
	0x62, 0x72, 0x61, 0x69, 0x6e, 0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kubebrainz_proto_rawDescOnce sync.Once
	file_kubebrainz_proto_rawDescData = file_kubebrainz_proto_rawDesc
)

func file_kubebrainz_proto_rawDescGZIP() []byte {
	file_kubebrainz_proto_rawDescOnce.Do(func() {
		file_kubebrainz_proto_rawDescData = protoimpl.X.CompressGZIP(file_kubebrainz_proto_rawDescData)
	})
	return file_kubebrainz_proto_rawDescData
}

var file_kubebrainz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubebrainz_proto_goTypes = []any{
	(*StatusRequest)(nil),     // 0: kubebrainz.StatusRequest
	(*StatusResponse)(nil),    // 1: kubebrainz.StatusResponse
	(*GetArtistRequest)(nil),  // 2: kubebrainz.GetArtistRequest
	(*GetArtistResponse)(nil), // 3: kubebrainz.GetArtistResponse
}
var file_kubebrainz_proto_depIdxs = []int32{
	0, // 0: kubebrainz.PStoreService.Status:input_type -> kubebrainz.StatusRequest
	2, // 1: kubebrainz.PStoreService.GetArtist:input_type -> kubebrainz.GetArtistRequest
	1, // 2: kubebrainz.PStoreService.Status:output_type -> kubebrainz.StatusResponse
	3, // 3: kubebrainz.PStoreService.GetArtist:output_type -> kubebrainz.GetArtistResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubebrainz_proto_init() }
func file_kubebrainz_proto_init() {
	if File_kubebrainz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kubebrainz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubebrainz_proto_goTypes,
		DependencyIndexes: file_kubebrainz_proto_depIdxs,
		MessageInfos:      file_kubebrainz_proto_msgTypes,
	}.Build()
	File_kubebrainz_proto = out.File
	file_kubebrainz_proto_rawDesc = nil
	file_kubebrainz_proto_goTypes = nil
	file_kubebrainz_proto_depIdxs = nil
}
